icinga_master_fqdn: "{{ hostvars['master1']['fqdn'] | default(hostvars['master1']['ansible_host']) }}"
icinga_master_host: "{{ hostvars['master1']['ansible_host'] }}"
db_host: "{{ hostvars['master1']['ansible_host'] }}"
icinga_master_invhost: "{{ hostvars['master1']['inventory_hostname'] }}"
icinga_url: "http://{{ icinga_master_host }}/icingaweb2"
icinga_user: "icingaadmin"
icinga_pass: "icingaadmin"