
- name: Deploy Director config
  listen: deploy_director 
  telekom_mms.icinga_director.icinga_deploy:
    url: "{{ icinga_url }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    timeout: 30