- name: configure database
  hosts: master
  become: true
  roles:
    - geerlingguy.mysql
  vars:
    mysql_databases:
      - name: icingadb
      - name: icingaweb
      - name: director
        encoding: utf8mb4
        collation: utf8mb4_general_ci
    mysql_users:
      - name: icingadb-user
        host: "%"
        password: icingadb-password
        priv: "icingadb.*:ALL"
      - name: icingaweb-user
        priv: "icingaweb.*:ALL"
        host: "%"
        password: icingaweb-password
      - name: director-user
        host: "%"
        priv: "director.*:ALL"
        password: director-password